name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag lscanferlato/countdown:latest
    - name: Log in to registry
      run: docker login -u lscanferlato -p ${{secrets.DOCKER_HUB_TOKEN}}
    - name: push image to dockerhub
      run: 
        docker push lscanferlato/countdown:latest
